### ISSUE TITLE
No strings found. skipping writing to a bundle.l10n.json

### ISSUE THREAD

**Issue by R-Alothaim** [microsoft/vscode-l10n#105]
Whenever I execute ```npx @vscode/l10n-dev export --outDir ./l10n ./src``` I receive ```searching for typescript/javascript files... found 6 typescript files. extracting strings... no strings found. skipping writing to a bundle.l10n.json.```
I'm not sure if this issue is from the [source file](https://github.com/dzhavat/css-flexbox-cheatsheet), or from my execution.
What I did exactly is I entered the command inside the extension folder.

**Comment by TylerLeonhardt** [comment]
Do you have any strings that are marked as localization strings using the `vscode.l10n.t(...)` API?

**Comment by TylerLeonhardt** [comment]
Here's a sample:

https://github.com/microsoft/vscode-extension-samples/blob/main/l10n-sample/README.md

And I did a livestream on this API at the 22nd minute 

https://www.youtube.com/live/djPddDUn44o?feature=share

Hope that helps!
