### ISSUE TITLE
Passing outDir to command always outputs warning that it doesn't match packageJSON.l10n value.

### ISSUE THREAD

**Issue by dbreese** [microsoft/vscode-l10n#115]
In package.json, I have 
```
  "l10n": "./l10n",
```

When I run the command `npx @vscode/l10n-dev export -o ./l10n ./src`, It always outputs 

```
The l10n property in the package.json does not match the outDir specified. For an extension to work correctly, l10n must be set to the location of the bundle files.
```

But the code seems to succeed.

I think the comparison here just needs to use !==?

https://github.com/microsoft/vscode-l10n/blob/7b8902c42dfa21872d8417a37ecb0ac429840c7d/l10n-dev/src/cli.ts#L164-L170

**Comment by jruales** [comment]
I'm also running into this issue.

**Comment by TylerLeonhardt** [comment]
🤦 nice find! PR out to fix that.

**Comment by dbreese** [comment]
Thanks, @TylerLeonhardt I was going to submit a PR, but couldn't get the tests to run locally, and the few things I tried I couldn't get working:

```
$ npm run build-wasm

> @vscode/l10n-dev@0.0.26 build-wasm
> npm run build-wasm-typescript && npm run build-wasm-tsx


> @vscode/l10n-dev@0.0.26 build-wasm-typescript
> tree-sitter build-wasm ./node_modules/tree-sitter-typescript/typescript && mv ./tree-sitter-typescript.wasm ./src/ast/tree-sitter-typescript.wasm

emcc command failed - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

**Comment by TylerLeonhardt** [comment]
> Is the docker daemon running?

You need to have docker running in order for this command to work
