### ISSUE TITLE
Cannot export value on Variable or Template String

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode-l10n#130]
For example, the following two cases cannot be scanned by l10-dev:

```
import { l10n } from 'vscode';

const a = 'vscode-l10n-dev';
console.log(l10n.t(a));
console.log(l10n.t(`${a}`));
```

**Comment by TylerLeonhardt** [comment]
This is by designed. We extract translations statically without running the actual extension code. It is extremely difficult to extract something like this unless they were simple like your case.

As for template strings, that's tracked in #78

**Comment by yiliang114** [comment]
> This is by designed. We extract translations statically without running the actual extension code. It is extremely difficult to extract something like this unless they were simple like your case.
> 
> As for template strings, that's tracked in #78

That's true.
