### ISSUE TITLE
How to keep '\u200b' in generated xlf file?

### ISSUE THREAD

**Issue by Cosifne** [microsoft/vscode-l10n#131]
We have links need translated like https://github.com/dotnet/vscode-csharp/blob/a62858ca0eaaf750d3aff17c87e52d4ca779891b/package.nls.json#L248 includes `\u200b`
However, when I run `generate-xlf`, `\u200b` is not reserved in the xlf files.
![image](https://github.com/microsoft/vscode-l10n/assets/24360909/b93a8a9f-5c65-44a2-8029-a535cb04cf32)
![image](https://github.com/microsoft/vscode-l10n/assets/24360909/66ed2258-753e-46b6-916f-2c80a856a16a)

This is causing the localization engine to remove `\u200b` from the link.
https://github.com/dotnet/vscode-csharp/pull/6388/files
Is there any way to keep the character

**Comment by Cosifne** [comment]
Tag @TylerLeonhardt to help

**Comment by TylerLeonhardt** [comment]
I just tried this and I can't repro:

package.nls.json:
```json
{
    "generateOptionsSchema.symbolOptions.searchMicrosoftSymbolServer.description": {
        "message": "If 'true' the Microsoft Symbol server (https\u200b://msdl.microsoft.com\u200b/download/symbols) is added to the symbols search path. If unspecified, this option defaults to 'false'.",
        "comment": [
          "We use '\u200b' (unicode zero-length space character) to break VS Code's URL detection regex for URLs that are examples. Please do not translate or localized the URL.",
          "{Locked='(https\u200b://msdl.microsoft.com\u200b/download/symbols)'}"
        ]
    }
}
```
Command output:
```
>> npx @vscode/l10n-dev@latest generate-xlf ./package.nls.json -o foo.xlf
Searching for L10N JSON files...
Found 1 L10N JSON files. Generating XLF...
Wrote XLF file to: foo.xlf
```
Resulting XLF:
<img width="1155" alt="image" src="https://github.com/microsoft/vscode-l10n/assets/2644648/db396a62-f283-454e-aef1-6f3e1d67aed1">
Raw XLF if you want to copy and verify yourself:
```xlf
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file original="package" source-language="en" datatype="plaintext"><body>
    <trans-unit id="generateOptionsSchema.symbolOptions.searchMicrosoftSymbolServer.description">
      <source xml:lang="en">If &apos;true&apos; the Microsoft Symbol server (https​://msdl.microsoft.com​/download/symbols) is added to the symbols search path. If unspecified, this option defaults to &apos;false&apos;.</source>
      <note>We use &apos;​&apos; (unicode zero-length space character) to break VS Code&apos;s URL detection regex for URLs that are examples. Please do not translate or localized the URL.
{Locked=&apos;(https​://msdl.microsoft.com​/download/symbols)&apos;}</note>
    </trans-unit>
  </body></file>
</xliff>
```

Are you able to repro this locally?

**Comment by Cosifne** [comment]
Ah I just checked the loc content looks like it is actually perserved. (Just Github doesn't show it in the PR) Close this issue.
Thanks Tyler!
