### ISSUE TITLE
Possible optimization: skip regex replacement when there are no replacement arguments

### ISSUE THREAD

**Issue by jruales** [microsoft/vscode-l10n#135]
Looking at the file [l10n/src/main.ts](https://github.com/microsoft/vscode-l10n/blob/main/l10n/src/main.ts#L226) it seems like it's always running a regex replace, even if the call to `t()` didn't receive any replacement args. I'm thinking that there could be an optimization where the program just returns the unchanged string in such cases, instead of running a no-op regex replacement.

**Comment by TylerLeonhardt** [comment]
Yeah good point. A simple check like:
```
Object.keys(values).length
```

would be a minor optimization. Any interest in submitting a PR? This is a pretty quick fix.

**Comment by jruales** [comment]
@TylerLeonhardt I've created the PR. Do you know if this would need to be done in `vscode.l10n.t()` as well? Where's the code for that?

**Comment by jruales** [comment]
I've created another PR for that too. See: https://github.com/microsoft/vscode/pull/194854
