### ISSUE TITLE
We don't scan when variables are declared elsewhere `let l10n; l10n = require('vscode').l10n`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-l10n#51]
Needed for https://github.com/microsoft/vscode-emmet-helper/pull/71

**Comment by rzhao271** [comment]
Marking as verification-found for now due to https://github.com/microsoft/vscode-emmet-helper/pull/71#issuecomment-1316054230.

**Comment by TylerLeonhardt** [comment]
Fixed in #64 pending release
