### ISSUE TITLE
Issues with `@vscode/l10n-dev` tool (documentation?)

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-l10n#53]
Hi,

I'm having a few issues with the `@vscode/l10n-dev` tool, to extract the strings from my source. I guess the instructions in README.md are outdated. If that's the case, I would be glad to open a PR to fix it

1. The `npx @vscode/l10n-dev ./src --out ./l10n` command didn't work for me. Neither installing the tool with `npm install -g`. After digging a bit, I find out I had to add an `export` command

2.  It seems there is a typo in the `--out` parameter. Looking at the source, I find out it should be `--o` or `--outDir` instead

In the end, the correct command to me was

```
    npx @vscode/l10n-dev export ./src --outDir ./l10n
```

Thank you

**Comment by TylerLeonhardt** [comment]
Nice catch! Fixed in ^^^
