### ISSUE TITLE
The output file should be _formatted_

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-l10n#54]
Hi,

The output `bundle.l10n.json` file should be formatted, with line breaks and space/tabs, for easier reading and processing.

Thank you

**Comment by TylerLeonhardt** [comment]
Verification (when PR goes in):

* go to an extension and add a `vscode.l10n.t(...)` somewhere
* `npx @vscode/l10n-dev export ./src
* open the generated `bundle.l10n.json`

it should be formatted nicely.

**Comment by alefragnani** [comment]
Thank you, and congrats for the tool/API 👍
