### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by deakjahn** [microsoft/vscode-l10n#61]
Dear me. :-) I know it's not the best place to ask but how do you use it? Documentation seems to be very contradicting, [some](https://code.visualstudio.com/api/references/vscode-api#l10n) suggest to use the `vscode/l10n` dependency, [others](https://github.com/microsoft/vscode-l10n) say it's built-in already if you only want to use in the main extension. `package.nls.json` gets picked up all right but I simply can't make the `bundle.l10n.json` work.

Without the dependency, trying to use `vscode.l10n.t()` gives an error of _Property 'l10n' does not exist on type 'typeof import("vscode")._

If I do depend on the package, then I can import:

    import { t } from "@vscode/l10n";

And it looks like it might work but then comes a very nasty surprise: is it real that, in the bundle files, I have to use the English original as a key? Can't I use a **key** like in the package level? Eg:

    "extension.key1.text": "first text",
    "extension.key2.text": "second text",
    "extension.key3.text": "third text",

Really? I hope not because this would be rather problematic. After all, the same original won't always be translated to the same localized string. There are homonyms in English. There might be situations when the same expression has to be spelled, cased or translated differently, depending on context. Tell me I misunderstood something...

**Comment by TylerLeonhardt** [comment]
@deakjahn whether to use the built-in API or `@vscode/l10n` depends on where the code is running.

If you have access to the built-in API (meaning your code is running in the main extension host process) then you use the built-in API.

If you are running code _outside_ of that in a separate process that you would also like to localize, you can use `@vscode/l10n`. This is a more advanced scenario but is needed for things like language servers.

**Comment by TylerLeonhardt** [comment]
With that said,

> ```
> import { t } from "@vscode/l10n";
> ```

I don't think I support this form of import. For now, this has to be:

```
import * as l10n from "@vscode/l10n";
```

I'm working on catching these edge cases.

Note this should work (if you're running in the extension host):

```
import { l10n } from "vscode";
```

**Comment by deakjahn** [comment]
Sorry, but there's the rub. That's why I wrote in the first place. :-)

    import { l10n } from "vscode";

doesn't work (neither does the variation with asterisk and referencing it by name). Red squiggly under `l10n` and the error message as above. I'm in VS Code 1.73.1, it says no update is available, it's fresh.

**Comment by deakjahn** [comment]
As to the other issue, couldn't that be solved so that we can have our cake and eat it, too? Considering that it would also solve  the other [issue](https://github.com/microsoft/vscode-l10n/issues/60) of not yet thinking about people who need something else than English as their neutral, fallback language?

Basically, what I would suggest is to make use of `bundle.l10n.json` if present, and no change if it isn't. Right now, we're expected to provide:

* no file for the neutral language, the string comes directly from the `t()` parameter;
* `bundle.l10n.locale.json` for any other language, the string comes keyed by the `t()` parameter;

Adding `bundle.l10n.json` would simply mean that the neutral language is also looked up, keyed by the `t()` parameter

* `bundle.l10n.json` for the neutral language, the string comes keyed by the `t()` parameter;
* `bundle.l10n.locale.json` for any other language, the string comes keyed by the `t()` parameter;

This second would solve the remaining problems. First, we would be free to use whatever key we like, be it a real key or the original string. Second, it would also solve the fallback language problem, the neutral bundle could contain any language, not just English. Those whole want to use a different language and localize to English instead of the other way around would simply provide a `bundle.l10n.en.json` file.

Besides, all those current or future users who don't use such a neutral bundle would receive the current treatment without any breaking change.

**Comment by TylerLeonhardt** [comment]
What engine version are you using in the package.json? What @types/vscode version are you using in the package.json?

**Comment by deakjahn** [comment]
I have:

    "engines": {
      "vscode": "^1.52.0"
    },

    "@types/vscode": "~1.52.0",

I never thought that I had to keep track of new versions myself, none of the other platforms I develop on make me do so. Do I really need to?

Fair enough, I don't know about extracting `t()`, I didn't use that.

**Comment by TylerLeonhardt** [comment]
I'm going to update the docs to include this engine.

**Comment by deakjahn** [comment]
Yep, that did the trick, thanks.

I we could only convice you to support `bundle.l10n.json` directly, as mentioned above, both to be able to use keys and to support non-English default scenarions, we would be really happy bunnies... :-)

**Comment by TylerLeonhardt** [comment]
PR out to update README... let's talk "default language" in the issue dedicated to it https://github.com/microsoft/vscode-l10n/issues/60
