### ISSUE TITLE
Unexpected Behavior - Translation notes are appended to the English string when no translation is provided

### ISSUE THREAD

**Issue by tehcrashxor** [microsoft/vscode-l10n#62]
When a translation is not provided for a string, I would expect that just the default English string would be used as a fallback.  However, it appears that `vscode.l10n.t(...)` is instead using a concatenation of the string and the translation notes.

For a simple example:
```typescript
vscode.window.showInformationMessage(vscode.l10n.t({
    message: "Untranslated Test String 1", comment: ["Translation notes 1"]}));
vscode.window.showInformationMessage(vscode.l10n.t({
    message: "Untranslated Test String 2", comment: ["Translation notes 2"]}));
```
with a `bundle.l10n.fr.json` which only translates one of those strings like
```json
{
  "Untranslated Test String 1/Translation notes 1": "Fake Translation String 1"
}
```
we get the expected output when VS Code is set to English:
![image](https://user-images.githubusercontent.com/3751389/204630564-aee136d9-e864-422d-b377-3b1933b4cfb2.png)
but switching to French ends up appending the translation notes for the one untranslated string:
![image](https://user-images.githubusercontent.com/3751389/204630848-38c9f9d5-fc11-45ab-a6d1-f0ca28db9850.png)

**Comment by TylerLeonhardt** [comment]
I thought I fixed this in Insiders. Are you using vscode stable?

**Comment by tehcrashxor** [comment]
Ah, that is correct - issue exists in stable v1.73.1, but works as expected in v1.74.0-insider

**Comment by TylerLeonhardt** [comment]
The next stable will be out next week so since there's no action left here, I'll close it
