### ISSUE TITLE
Improve CLI (@vscode/l10n-dev ) - Use `l10n` entry in `package.json` if `--outDir` param is missing

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-l10n#66]
An improvement to the CLI - (@vscode/l10n-dev), specially for newcomers, I would suggest:

- [ ] Use the value defined in l10n entry, if --outDir param is missing

_Originally posted by @alefragnani in https://github.com/microsoft/vscode-l10n/issues/59_

**Comment by TylerLeonhardt** [comment]
This is in now

**Comment by TylerLeonhardt** [comment]
Oops sorry it's not just yet 😆
