### ISSUE TITLE
`l10n.t('foo\'bar')` is being extracted as `foo\'bar` but really it should honor escape characters

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-l10n#73]

**Comment by TylerLeonhardt** [comment]
Verification:

in an extension.ts file:
```
import { l10n } from 'vscode';
l10n.t('foo \' bar');
```

exporting that using:

```
npx @vscode/l10n-dev export ./extension.ts
```

should get you a file with:
```
{
  "foo ' bar": "foo ' bar"
}
```

**Comment by connor4312** [comment]
There remains a bug here: if the escaped character is anything but the quote style used for the string, then it gets double-escaped, for example `l10n.t('hello \" world')`

**Comment by TylerLeonhardt** [comment]
I think it probably needs to end up being `hello " world` because:
```
> console.log('sd\"sa')
sd"sa
```
