### ISSUE TITLE
import-xlf prettified output

### ISSUE THREAD

**Issue by tehcrashxor** [microsoft/vscode-l10n#75]
`npx @vscode/l10n-dev import-xlf ...` produces the translated `bundle.l10n.*.json` files as single lines, which makes diffing the output annoying without manually invoking the VS Code Format Document command for each translated bundle after every import.

It would be much more convenient if the tool would prettify/format the outputted bundles.

**Comment by TylerLeonhardt** [comment]
Nice catch, probably just need to update:
https://github.com/microsoft/vscode-l10n/blob/main/l10n-dev/src/cli.ts#L212

to use `JSON.stringify(..., null, 4)`

I've got a few items on my plate right now, so I can't get to this right away... but if you'd like to contribute, this is a very low hanging fruit!
