### ISSUE TITLE
Docs for @vscode/l10n disagree with TS Types

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-l10n#79]
In the readme https://github.com/microsoft/vscode-l10n/tree/main/l10n

- There's a function `l10n.config` on the exported `l10n` type, but `l10n` is actually a function with no `config` property
- `t` is an exported member from the module, not a property of `l10n`

**Comment by TylerLeonhardt** [comment]
oops https://github.com/microsoft/vscode-l10n/pull/80
