### ISSUE TITLE
esm variant (`module`) does not not implement `fsPath`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-l10n#81]
The package.json defines a `module` field to provide a esm variant.

Packagers like esbuild and webpack use that to tree shake.

The problem is that `module` is currently set to `./dist/browser.esm.js` and is not defined for NodeJS: it does not implement the `fsPath` config and uses `fetch (requires > Node 17.5). It should instead match the NodeJS variant (`main.esm.js`)

See https://esbuild.github.io/api/#main-fields:
> For package authors: Some packages incorrectly use the module field for browser-specific code, leaving node-specific code for the main field. This is probably because node ignores the module field and people typically only use bundlers for browser-specific code. However, bundling node-specific code is valuable too (e.g. it decreases download and boot time) and packages that put browser-specific code in module prevent bundlers from being able to do tree shaking effectively. If you are trying to publish browser-specific code in a package, use the browser field instead.

**Comment by andreamah** [comment]
Are there some verif steps for this?

**Comment by TylerLeonhardt** [comment]
Yeah I guess maybe just look at the package.json:
https://github.com/microsoft/vscode-l10n/blob/main/l10n/package.json

and see if there's a `module` entrypoint anymore. It would be at the same level as `main` and `browser`.

This is verified if you don't see it.
